# Generated by Django 5.1.6 on 2025-03-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='base_currency_code',
            new_name='base_code',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='target_currency_code',
            new_name='target_code',
        ),
    ]
