# Generated by Django 5.1.6 on 2025-03-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_rename_base_currency_code_currency_base_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='base_code',
            new_name='base_currency_code',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='target_code',
            new_name='target_currency_code',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='base_currency',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='target_currency',
        ),
        migrations.AddField(
            model_name='currency',
            name='base_currency_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='currency',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='currency',
            name='target_currency_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
