# Generated by Django 5.1.6 on 2025-03-24 07:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_alter_currency_base_currency_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='notify_time',
        ),
        migrations.AddField(
            model_name='user',
            name='notify_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
